import graphicDesignImg from '../assets/graphic_design_work.jpg';
import designSystemImg from '../assets/design_system_work.jpg';
import componentMakingImg from '../assets/component_making_work.jpg';

export const mockUsers = [
  { id: 'u1', name: 'Darlene Robertson', initials: 'DR', color: '#3b82f6', role: 'UI/UX Designer' },
  { id: 'u2', name: 'Savannah Nguyen', initials: 'SN', color: '#10b981', role: 'Frontend Developer' },
  { id: 'u3', name: 'Leslie Alexander', initials: 'LA', color: '#f59e0b', role: 'Product Manager' },
  { id: 'u4', name: 'Brooklyn Simmons', initials: 'BS', color: '#8b5cf6', role: 'QA Engineer' },
  { id: 'u5', name: 'Guy Hawkins', initials: 'GH', color: '#ec4899', role: 'SEO Specialist' },
  { id: 'u6', name: 'Eleanor Pena', initials: 'EP', color: '#ef4444', role: 'Marketing Lead' },
];

export const mockTasks = [
  {
    id: 't1',
    title: 'Darlene Robertson',
    description: 'Lorem Ipsum is simply dummy text printing and typesetting industry. Lorem Ipsum has been...',
    status: 'todo',
    date: '02/24 12:11 PM',
    integration: 'github',
    creatorId: 'u1',
    assignees: ['u1', 'u2', 'u3'],
    image: null,
    totalAssigneesCount: 8,
    priority: 'high',
    progress: 15,
    estimatedTime: '12h',
  },
  {
    id: 't2',
    title: 'Savannah Nguyen',
    description: '',
    status: 'todo',
    date: '04/24 1:14 PM',
    integration: 'gmail',
    creatorId: 'u2',
    assignees: ['u2'],
    image: null,
    totalAssigneesCount: 1,
    priority: 'low',
    progress: 40,
    estimatedTime: '2h',
  },
  {
    id: 't3',
    title: 'Darlene Robertson',
    description: 'Lorem Ipsum is simply dummy text into a printing and typesetting.',
    status: 'todo',
    date: '11/23 2:44 AM',
    integration: 'discord',
    creatorId: 'u1',
    assignees: ['u1', 'u4', 'u5'],
    image: null,
    totalAssigneesCount: 6,
    priority: 'medium',
    progress: 0,
    estimatedTime: '6h',
  },
  {
    id: 't4',
    title: 'Leslie Alexander',
    description: 'Do the best password option when login & send email for doing this...',
    status: 'inprogress',
    date: '02/22 09:33 AM',
    integration: 'slack',
    creatorId: 'u3',
    assignees: ['u3'],
    image: null,
    totalAssigneesCount: 1,
    priority: 'high',
    progress: 60,
    estimatedTime: '8h',
  },
  {
    id: 't5',
    title: 'Graphic Design Work',
    description: 'Create aesthetic marketing visuals and graphics for the product landing page.',
    status: 'inprogress',
    date: '02/22 09:33 AM',
    integration: 'messenger',
    creatorId: 'u3',
    assignees: ['u3', 'u1'],
    image: graphicDesignImg,
    totalAssigneesCount: 2,
    priority: 'medium',
    progress: 45,
    estimatedTime: '3d',
  },
  {
    id: 't6',
    title: 'Brand Guideline Design',
    description: 'Design the core brand book guidelines and color schemes for marketing.',
    status: 'inreview',
    date: '02/22 09:33 AM',
    integration: 'gmail',
    creatorId: 'u1',
    assignees: ['u2'],
    image: null,
    totalAssigneesCount: 1,
    priority: 'low',
    progress: 85,
    estimatedTime: '5d',
  },
  {
    id: 't7',
    title: 'Competitor Analysis',
    description: 'Do the best password option when login & send email for doing this...',
    status: 'inreview',
    date: '02/22 09:33 AM',
    integration: 'github',
    creatorId: 'u4',
    assignees: ['u4'],
    image: null,
    totalAssigneesCount: 1,
    priority: 'medium',
    progress: 70,
    estimatedTime: '16h',
  },
  {
    id: 't8',
    title: 'Design System Work',
    description: 'Maintain and update the core Figma files and React components for the styleguide.',
    status: 'inreview',
    date: '02/22 09:33 AM',
    integration: 'messenger',
    creatorId: 'u1',
    assignees: ['u1', 'u2'],
    image: designSystemImg,
    totalAssigneesCount: 2,
    priority: 'high',
    progress: 90,
    estimatedTime: '10d',
  },
  {
    id: 't9',
    title: 'Component Making Work',
    description: 'Create the pixel-perfect design-system components and responsive grids.',
    status: 'done',
    date: '12/22 6:16 PM',
    integration: 'teams',
    creatorId: 'u4',
    assignees: ['u4'],
    image: componentMakingImg,
    totalAssigneesCount: 1,
    priority: 'high',
    progress: 100,
    estimatedTime: '4d',
  },
  {
    id: 't10',
    title: 'Brooklyn Simmons',
    description: 'Lorem Ipsum is simply dummy text printing and typesetting industry. Lorem Ipsum has been...',
    status: 'done',
    date: '11/23 4:28 PM',
    integration: 'slack',
    creatorId: 'u4',
    assignees: ['u4', 'u6'],
    image: null,
    totalAssigneesCount: 4,
    priority: 'low',
    progress: 100,
    estimatedTime: '1.5d',
  },
];
